In [1]:
import pandas as pd
df = pd.read_csv('salaries_by_college_major.csv')
df.head()

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
0,Accounting,46000.0,77100.0,42200.0,152000.0,Business
1,Aerospace Engineering,57700.0,101000.0,64300.0,161000.0,STEM
2,Agriculture,42600.0,71900.0,36300.0,150000.0,Business
3,Anthropology,36800.0,61500.0,33800.0,138000.0,HASS
4,Architecture,41600.0,76800.0,50600.0,136000.0,Business

# Data Exploration and Data Cleaning

In [2]:
df.shape

(51, 6)

In [3]:
df.columns

Index(['Undergraduate Major', 'Starting Median Salary',
       'Mid-Career Median Salary', 'Mid-Career 10th Percentile Salary',
       'Mid-Career 90th Percentile Salary', 'Group'],
      dtype='object')

In [4]:
df.isna().values.any()

True

In [5]:
df.head()
df.tail()

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
46,Psychology,35900.0,60400.0,31600.0,127000.0,HASS
47,Religion,34100.0,52000.0,29700.0,96400.0,HASS
48,Sociology,36500.0,58200.0,30700.0,118000.0,HASS
49,Spanish,34000.0,53100.0,31000.0,96400.0,HASS
50,Source: PayScale Inc.,NaN,NaN,NaN,NaN,NaN

In [6]:
clean_df = df.dropna()
clean_df.tail()

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
45,Political Science,40800.0,78200.0,41200.0,168000.0,HASS
46,Psychology,35900.0,60400.0,31600.0,127000.0,HASS
47,Religion,34100.0,52000.0,29700.0,96400.0,HASS
48,Sociology,36500.0,58200.0,30700.0,118000.0,HASS
49,Spanish,34000.0,53100.0,31000.0,96400.0,HASS

In [8]:
clean_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 50 entries, 0 to 49
Data columns (total 6 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Undergraduate Major                50 non-null     object
 1   Starting Median Salary             50 non-null     float64
 2   Mid-Career Median Salary           50 non-null     float64
 3   Mid-Career 10th Percentile Salary  50 non-null     float64
 4   Mid-Career 90th Percentile Salary  50 non-null     float64
 5   Group                              50 non-null     object
dtypes: float64(4), object(2)
memory usage: 2.7+ KB

# Highest and Lowest Earning Degrees

In [ ]:
print(clean_df['Mid-Career Median Salary'].max())
print(f"Index for the max mid career salary: {clean_df['Mid-Career Median Salary'].idxmax()}")
clean_df['Undergraduate Major'][8]

107000.0
Index for the max mid career salary: 8

'Chemical Engineering'

In [ ]:
print(clean_df['Starting Median Salary'].min())
clean_df['Undergraduate Major'].loc[clean_df['Starting Median Salary'].idxmin()]

34000.0

'Spanish'

In [ ]:
clean_df.loc[clean_df['Mid-Career Median Salary'].idxmin()]

Undergraduate Major                  Education
Starting Median Salary                   34900
Mid-Career Median Salary                 52000
Mid-Career 10th Percentile Salary        29300
Mid-Career 90th Percentile Salary       102000
Group                                     HASS
Name: 18, dtype: object

# Majors with the Most Potential vs Lowest Risk

In [ ]:
spread_col = clean_df['Mid-Career 90th Percentile Salary'] - clean_df['Mid-Career 10th Percentile Salary']
clean_df.insert(1, 'Spread', spread_col)
clean_df.head()

     Undergraduate Major    Spread  ...  Mid-Career 90th Percentile Salary     Group
0             Accounting  109800.0  ...                           152000.0  Business
1  Aerospace Engineering   96700.0  ...                           161000.0      STEM
2            Agriculture  113700.0  ...                           150000.0  Business
3           Anthropology  104200.0  ...                           138000.0      HASS
4           Architecture   85400.0  ...                           136000.0  Business

[5 rows x 7 columns]

In [ ]:
low_risk = clean_df.sort_values('Spread')
low_risk[['Undergraduate Major', 'Spread']].head()

           Undergraduate Major   Spread
40                     Nursing  50700.0
43         Physician Assistant  57600.0
41                   Nutrition  65300.0
49                     Spanish  65400.0
27  Health Care Administration  66400.0

# Degrees with the Highest Potential

In [ ]:
highest_potential = clean_df.sort_values('Mid-Career 90th Percentile Salary', ascending=False)
highest_potential[['Undergraduate Major', 'Mid-Career 90th Percentile Salary']].head()

     Undergraduate Major  Mid-Career 90th Percentile Salary
17             Economics                           210000.0
22               Finance                           195000.0
8   Chemical Engineering                           194000.0
37                  Math                           183000.0
44               Physics                           178000.0

In [ ]:
highest_spread = clean_df.sort_values('Spread', ascending=False)
highest_spread[['Undergraduate Major', 'Spread']].head()

   Undergraduate Major    Spread
17           Economics  159400.0
22             Finance  147800.0
37                Math  137800.0
36           Marketing  132900.0
42          Philosophy  132500.0

In [ ]:
highest_spread = clean_df.sort_values('Mid-Career Median Salary', ascending=False)
highest_spread[['Undergraduate Major', 'Mid-Career Median Salary']].head()

       Undergraduate Major  Mid-Career Median Salary
8     Chemical Engineering                  107000.0
12    Computer Engineering                  105000.0
19  Electrical Engineering                  103000.0
1    Aerospace Engineering                  101000.0
17               Economics                   98600.0

# Group-wise Stats

In [ ]:
clean_df.groupby('Group').count()

          Undergraduate Major  ...  Mid-Career 90th Percentile Salary
Group                          ...
Business                   12  ...                                 12
HASS                       22  ...                                 22
STEM                       16  ...                                 16

[3 rows x 6 columns]

In [ ]:
pd.options.display.float_format = '{:,.2f}'.format
clean_df.groupby('Group').mean()

             Spread  ...  Mid-Career 90th Percentile Salary
Group                ...
Business 103,958.33  ...                         147,525.00
HASS      95,218.18  ...                         129,363.64
STEM     101,600.00  ...                         157,625.00

[3 rows x 5 columns]